import sqlite3

# Connect to the database (or create it)
conn = sqlite3.connect('bus_routes.db')
cursor = conn.cursor()

# Create a table
cursor.execute("CREATE TABLE IF NOT EXISTS buses (bus_number varchar(15),stops char(30) )")

# Insert sample data
bus_no=["505"]
bus_stop=["Mehdipatnam Bus Station",
]
for i in range(1):
   cursor.execute("insert into buses values(?,?)",(bus_no[0],bus_stop[i]))

cursor.execute("delete from buses where bus_number='' ")
data=cursor.execute("select * from buses")
for i in data:
   print(i)
# Commit changes and close the connection
conn.commit()
conn.close()
ode\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher' '59843' '--' 'C:\Users\ketha\OneDrive\Desktop\bus\database.py' 
('1', 'Afzal Gunj Bus Stop')
('1', 'Chatrapathi Shivaji Pul')
('1', 'Gowliguda Bus Depot')
('1', 'Central Bus Station (CBS)')
('1', 'Mahatma Gandhi Bus Station')
('1', 'Putlibowli Bus Stop')
('1', 'Bank Street')
('1', 'Koti Maternity Hospital')
('1', 'Sultan Bazar Bus Stop')
('1', 'Ram Koti Bus Stop')
('1', 'Kachiguda X Road')
('1', 'YMCA')
('1', 'Madapati Hanumantha School')
('1', 'YMCA')
('1', 'Narayanaguda Bus Stop')
('1', 'Chikkadpally Bus Stop')
('1', 'Golconda X Road')
('1', 'Raja Delux Bus Stop')
('1', 'Musheerabad')
('1', 'Padmarao Nagar')
('1', 'Chilkalguda Circle Bus Stop')
('1', 'Secunderabad/Chilkalguda Circle Bus Stop')
('2', 'Musheerabad')
('2', 'Raja Delux Bus Stop')
('2', 'Bakaram')
('2', 'Musheerabad Bus Stop')
('2', 'Bus Bhavan')
('2', 'VST Stop')
('2', 'Shankar Mutt')
('2', 'Nallakunta Bus Stop')
('2', 'Fever Hospital Bus Stop')
('2', 'Barkatpura Bus Stop')
('2', 'Cc Shroff Hospital')
('2', 'Kachiguda Bus Stop')
('2', 'Ram Koti')
('2', 'Koti Bus Stop')
('2', 'Shankar Mutt')
('2', 'Koti Bus Terminal')
('2', 'Koti Bus Stop')
('2', 'Koti')
('2', 'Putlibowli Bus Stop')
('2', 'Mahatma Gandhi Bus Station')
('3k', 'Koti Bus Terminal')
('3k', 'Koti Osmania Medical College')
('3k', 'Putili Bowli')
('3k', 'Chaderghat')
('3k', 'Koti Womens College')
('3k', 'Koti bus Stop')
('3k', 'Sultan Bazar')
('3k', 'Ram Koti Bus Stop')
('3k', 'Kachiguda X Road')
('3k', 'Kachiguda')
('3k', 'Tourist Hotel')
('3k', 'Barkatpura')
('3k', 'Fever Hospital')
('3k', 'Nallakunta')
('3k', 'Shankarmutt')
('3k', 'Vidyanagar Bus Stop')
('3k', 'Adikmet')
('3k', 'Adikmet')
('3k', 'Jamia Osmania')
('3k', 'Ladies Hostel (O.U. Campus)')
('3k', 'Osmania University (Campus)')
('3k', 'Manikeshwari Nagar')
('3k', 'Dairy Farm Bus Stop')
('3k', 'Tarnaka Hospital')
('3k', 'Tarnaka')
('3k', 'White House Bakery')
('3k', 'Lalapet Bus Stop')
('3k', 'Lalapet Bus Stop')
('3k', 'Moula Ali Railway Colony')
('3k', 'RPF Training Centre')
('3k', 'Upparguda X Road')
('3k', 'ZTS')
('3k', 'APIIC Colony (ZTS)')
('3k', 'Housing Board Colony Phase-I')
('3k', 'NRM College Bus Stop')
('3k', 'HB Colony')
('3k', 'APHB Colony')
('3k', 'Vasanth Vihar Colony')
('3k', 'SP Nagar')
('3k', 'Kushaiguda Depot')
('3k', 'South Kamalanagar Bus Stop')
('3k', 'ECIL X Road')
('3k', 'Kushaiguda Road')
('3k', 'Kushaiguda')
('3m', 'Afzalgunj Bus Terminus')
('3m', 'Chatrapathi Shivaji Pul')
('3m', 'Gowliguda Bus Depot')
('3m', 'Central Bus Station (CBS)')
('3m', 'Mahatma Gandhi Bus Station')
('3m', 'Putlibowli Bus Stop')
('3m', 'Bank Street')
('3m', 'Sultan Bazar Bus Stop')
('3m', 'Ram Koti Bus Stop')
('3m', 'Kachiguda X Road')
('3m', 'YMCA')
('3m', 'Madapati Hanumantha School')
('3m', 'YMCA')
('3m', 'Narayanaguda Bus Stop')
('3m', 'Baghlingampally')
('3m', 'Barkatpura Bus Stop')
('3m', 'Fever Hospital Bus Stop')
('3m', 'Nallakunta')
('3m', 'Shankarmutt Bus Stop')
('3m', 'Vidyanagar Bus Stop')
('3m', 'Vidyanagar')
('3m', 'Adikmet')
('3m', 'Ramnagar Gundu')
('3m', 'Ladies Hostel (O.U. Campus)')
('3m', 'Osmania University (Campus)')
('3m', 'Dairy Farm Bus Stop')
('3m', 'Tarnaka TSRTC Bus Stop')
('3m', 'Tarnaka')
('3m', 'White house Bus stop')
('3m', 'Lalapet Bus Stop')
('3m', 'Lalapet Bus Stop')
('3m', 'Moula Ali Railway Colony')
('3m', 'RPF Training Centre')
('3m', 'Upparguda X Road')
('3m', 'ZTS Bus Stop')
('3m', 'RTC Colony')
('3m', 'Shafi Nagar')
('3m', 'Bharat Nagar')
('3m', 'Ganesh Nagar Bus Stop')
('3m', 'Maruthi Nagar')
('3m', 'A.S.Rao Nagar Bus Stop')
('3m', 'A S Rao Nagar Bus')
('3', 'Afzalgunj Bus Terminus')
('3', 'Afzal Gunj Bus Stop')
('3', 'Chatrapathi Shivaji Pul')
('3', 'Gowliguda Bus Depot')
('3', 'Central Bus Station (CBS)')
('3', 'Mahatma Gandhi Bus Station')
('3', 'Chaderghat')
('3', 'Koti Womens College')
('3', 'Koti Maternity Hospital')
('3', 'Sultan Bazar Bus Stop')
('3', 'Ram Koti Bus Stop')
('3', 'Kachiguda X Road')
('3', 'Tourist Bus Stand')
('3', 'Barkatpura')
('3', 'Fever Hospital')
('3', 'Nallakunta')
('3', 'Shankarmutt Bus Stop')
('3', 'Vidyanagar Bus Stop')
('3', 'Vidyanagar')
('3', 'Adikmet')
('3', 'Jamia Osmania')
('3', 'Ladies Hostel (O.U. Campus)')
('3', 'Osmania University (Campus)')
('3', 'Manikeshwari Nagar')
('3', 'Dairy Farm Bus Stop')
('3', 'Tarnaka')
('3', 'White house Bus stop')
('3', 'Lalapet Bus Stop')
('3', 'Lalapet Bus Stop')
('3', 'Moula Ali Railway Colony')
('3', 'RPF Training Centre')
('3', 'Upparguda X Road')
('3', 'ZTS Bus Stop')
('3', 'ZTC Bus Stop')
('3', 'APIIC Colony (ZTS)')
('3', 'HB Colony 1st Phase')
('3', 'NRM College Bus Stop')
('3', 'Housing Board Colony Phase-II')
('3', 'APHB Colony')
('3', 'Vasanth Vihar Colony')
('3', 'S.P. Nagar Bus Stop')
('3', 'Kushaiguda Depot')
('3', 'South Kamalanagar Bus Stop')
('3', 'ECIL')
('3', 'ECIL X Road')
('3', 'ECIL Cross Roads Bus Stop')
('3', 'Kushaiguda Road')
('3', 'Kushaiguda Bus Stop')
('3', 'Nagarjuna Colony')
('3', 'Chakripuram')
('3', 'Nagaram Road')
('3', 'Chakripuram Road')
('3', 'Vijaya Hospital Road Nagaram')
('3', 'Nagaram Bus Stop')
('3', 'Sudha Hospital Dammiguda X Road Nagaram')
('3', 'Rampally X Road')
('3', 'Ahmedha Guda')
('3', 'Icomm')
('3', 'Bandlaguda')
('3', 'Rajiv Gruhakalpa Colony')
('6', 'Vst Bus Stop')
('6', 'Shankar Mutt')
('6', 'Nallakunta Bus Stop')
('6', 'Korantee')
('6', 'Fever Hospital')
('6', 'Barkatpura')
('6', 'Narayanguda')
('6', 'Himayath Nagar')
('6', 'Postoffice (Himyatnagar)')
('6', 'Urdu Hall')
('6', 'Liberty Bus Stop')
('6', 'Secretariat Bus Stop')
('6', 'Birla Mandir')
('6', 'Lakdikapool Bus Stop')
('6', 'Mahavir Hospital')
('6', 'Jntu (Masabtank)')
('6', 'Masab Tank Bus Stop')
('6', 'Golconda Hotel')
('6', 'Nmdc Bus Stop')
('6', 'Sarojini Bus Stop')
('6', 'Mehdipatnam Bus Stop')
('6', 'Rethibowli')
('6', 'Nanalnagar Bus Stop')
('6', 'Salarjung Colony')
('6', 'Tolichowki Bus Stop')
('7', 'Secunderabad Railway Station Bus Stop')
('7', 'Regimental Bazaar Bus Stop')
('7', 'Sangeeth')
('7', 'St Anns School South Bus Stop')
('7', 'Secunderabad-MCH-Office')
('7', 'Swimming Pool North Bus Stop')
('7', 'Paradise BSNL Complex')
('7', 'Paradise Bus Stop')
('7', 'MG Road')
('7', 'James Street East Bus Stop')
('7', 'Ranigunj Bus Stop')
('7', 'Boats Club (RP Road)')
('7', 'Tank Bund')
('7', 'DBR Mills')
('7', 'Liberty Bus Stop')
('7', 'Liberty')
('7', 'Basheerbagh (L.B. Stadium)')
('7', 'Nizam College Bus Stop')
('7', 'Abids Bus Stop')
('7', 'Abids')
('7', 'GPO')
('7', 'Mozamjahi Market')
('7', 'Koti')
('7', 'Putlibowli Bus Stop')
('7', 'Mahatma Gandhi Bus Station')
('8', 'Central Bus Station')
('8', 'Gowliguda Bus Depot')
('8', 'Chatrapathi Shivaji Pul')
('8', 'Afzalgung Central Library')
('8', 'Afzalgunj Bus Terminus')
('8', 'Osmania Hospital')
('8', 'Osmangunj Bus Station')
('8', 'Mozamjahi Market')
('8', 'Gandhi Bhavan Bus Stop')
('8', 'Latha Talkies')
('8', 'Nampally Railway Station')
('8', 'Nampally Public Garden')
('8', 'Public Gardens Bus Stop')
('8', 'Nampally Grand Plaza')
('8', 'Assembly Bus Stop')
('8', 'Ravindra Bharati Bus Stop')
('8', 'Accountant General (A & G) Office / Birla Mandir')
('8', 'Secretariat')
('8', 'TSRTC Pushpak')
('8', 'Tank Bund')
('8', 'DBR Mills')
('8', 'Tankbund Bus Stop')
('8', 'Boats Club Bus Stop')
('8', 'Ranigunj')
('8', 'Jeera Bus Stop')
('8', 'Bible House')
('8', 'Bata')
('8', 'Patny Center')
('8', 'Clock Tower')
('8', 'St Anns High School Bus Stop')
('8', 'Uppal Bus Stop (Secunderabad)')
('8', 'Rathifile Bus Station')
('8', 'Secunderabad Bus Stop')
('8', 'Secunderabad Bus Station 2')
('8a', 'Chandrayangutta X Road')
('8a', 'Falaknuma RLY Bridge')
('8a', 'Engine Bowli')
('8a', 'Shamsheergunj')
('8a', 'Aliyabad')
('8a', 'Sayed Ali Chabutra')
('8a', 'Lal Dharwaza Mode')
('8a', 'Shah Ali Banda X Road')
('8a', 'Himmathpura / Shali Banda')
('8a', 'Chowmahalla Palace')
('8a', 'Khilwat')
('8a', 'Lad Baza')
('8a', 'Moosa Bowli')
('8a', 'City College')
('8a', 'High Court')
('8a', 'Nayapul')
('8a', 'Afzalgunj')
('8a', 'Osmangunj')
('8a', 'Mozamjahi Market')
('8a', 'Abids (G.P.O.)')
('8a', 'Latha Talkies')
('8a', 'Nampally Railway Station')
('8a', 'Nampally Public Garden')
('8a', 'L B Stadium Bus Stop')
('8a', 'Basheerbagh')
('8a', 'Liberty')
('8a', 'Liberty – GHMC')
('8a', 'Mini Tankbund')
('8a', 'Tank Bund')
('8a', 'Boats Club')
('8a', 'Bible House')
('8a', 'Bata')
('8a', 'Patny Center')
('8a', 'Clock Tower')
('8a', 'Sangeeth')
('8a', 'Keys High School')
('8a', 'Secunderabad Railway Station')
('9', 'Charminar Bus Station')
('9', 'Charminar')
('9', 'Afzal Gunj Bus Stop')
('9', 'Chatrapathi Shivaji Pul')
('9', 'Gowliguda Bus Depot')
('9', 'Central Bus Station (CBS)')
('9', 'Putlibowli Bus Stop')
('9', 'Koti')
('9', 'Koti Bus Terminus')
('9', 'Koti Bank Street')
('9', 'Nampally Station Road Bus Stop')
('9', 'Public Gardens Bus Stop')
('9', 'Assembly Bus Stop')
('9', 'Lakdikapul Bus Stop')
('9', 'Chintal Basti')
('9', 'Khairtabad')
('9', 'Erramanzil')
('9', 'NIMS Bus Stop')
('9', 'Ameerpet Bus Stop')
('9', 'Mytrivanam Bus Stop')
('9', 'S R Nagar Bus Stop')
('9', 'E S I Bus Stop')
('9', 'Rythu Bazar Erragadda')
('9', 'Erragadda FCI')
('9', 'Erragadda Gokul Theater')
('9', 'Allwyn Erragadda')
('9', 'Erragadda Bus Stop')
('9', 'Allwyn Colony')
('9', 'Sanath Nagar Police Station')
('9', 'Sanath Nagar')
('9', 'Fateh Nagar')
('9', 'Valmiki Nagar')
('9', 'Fateh Nagar X Road')
('9', 'Balanagar Bus Stop')
('9', 'Hal')
('9', 'District Bus Stop')
('9', 'Ganesh Nagar Bus Stop')
('9', 'Chintal')
('9', 'HMT Factory')
('9', 'Gajula Ramam X Road')
('9', 'Shapur Nagar1')
('9', 'Shapur Nagar Bus Stand')
('9', 'Jeedimetla Substation')
('9', 'Jeedimetla Bus Stop')
('10', 'Secunderabad Bus Station 2')
('10', 'Clock Tower')
('10', 'Manju Theater')
('10', 'Swapnalok Complex')
('10', 'Paradise')
('10', 'Paradise')
('10', 'Anand Theatre Bus Stop')
('10', 'Begumpet Police Line')
('10', 'Police Lines South Bus Stop')
('10', 'Begumpet / Prakash Nagar')
('10', 'Begumpet / Shoppers Stop')
('10', 'Shyam Lal South Bus Stop')
('10', 'Begumpet – Hyderabad Public School')
('10', 'Begumpet Railway Station')
('10', 'Greenlands Bus Stop')
('10', 'Lalbungalow Bus Stop')
('10', 'Sheesh Mahal')
('10', 'Ameerpet')
('10', 'Mytrivanam Bus Stop')
('10', 'Maitrivanam Bus Stop')
('10', 'S R Nagar Bus Stop')
('10', 'E S I Bus Stop')
('10', 'Rythu Bazar Erragadda')
('10', 'Erragadda FCI')
('10', 'Erragadda Gokul Theater')
('10', 'Allwyn Erragadda')
('10', 'Erragadda Bus Stop')
('10', 'Allwyn Colony')
('10', 'Sanath Nagar Police Station')
('10', 'Sanath Nagar Bus Depot')
('14p', 'Secunderabad Railway Station Bus Stop')
('14p', 'Rathifile Bus Station')
('14p', 'Regimental Bazaar Bus Stop')
('14p', 'Sangeeth South Bus Stop')
('14p', 'Rail Nilayam Bus Stop')
('14p', 'Alugadda Bhavi')
('14p', 'Mettuguda Bus Stop')
('14p', 'Lalaguda Bus Stop')
('14p', 'Railway Girl’s High School Bus Stop')
('14p', 'Mazid Lalaguada')
('14p', 'Lalguda Railway Quarters')
('14p', 'Shanti Nagar')
('14p', 'Lalapet Bus Stop')
('14p', 'Lalapet Bus Stop')
('14p', 'Moula Ali Railway Colony')
('14p', 'Prashanth Nagar Bus Stop')
('16a', 'ECIL X Road Bus Terminal')
('16a', 'Kamla Nagar')
('16a', 'Kamla Nagar')
('16a', 'ECIL X Road')
('16a', 'Kamla Nagar')
('16a', 'Radhika')
('16a', 'Asrao Nagar')
('16a', 'Rukmini Puram')
('16a', 'Sainikpuri')
('16a', 'Vayupuri')
('16a', 'Neredmet X Road')
('16a', 'Neredmet X Road')
('16a', 'Vajpayee Nagar')
('16a', 'Old Police Station')
('16a', 'Three Temples')
('16a', 'Vinayak Nagar')
('16a', 'Krupa Complex')
('16a', 'Safilguda')
('16a', 'Safilguda')
('16a', 'Anand Bagh')
('16a', 'R.K. Nagar')
('16a', 'Vani Nagar')
('16a', 'Anutex')
('16a', 'Malkajgiri')
('16a', 'Sairam Theatre')
('16a', 'Mirzalguda')
('16a', 'North Lalaguda')
('16a', 'New Bridge')
('16a', 'Railway Hospital / Mettuguda')
('16a', 'Mettuguda')
('16a', 'Mettuguda')
('16a', 'Alugadda Bhavi Bus Stop')
('16a', 'Rail Nilayam')
('16a', 'Railway Officer Guest House Sangeeth')
('16a', 'Secunderabad (Towards Uppal)')
('17', 'Chilakalaguda')
('17', 'Rathifile Bus Station')
('17', 'Regimental Bazaar Bus Stop')
('17', 'Sangeeth South Bus Stop')
('17', 'Rail Nilayam Bus Stop')
('17', 'Alugadda Baavi South Bus Stop')
('17', 'Mettuguda')
('17', 'NIN/Water Tank Bus Stop')
('17', 'Tarnaka')
('17', 'White house Bus stop')
('17', 'Lalapet Bus Stop')
('17', 'Lalapet Bus Stop')
('17', 'Moula Ali Railway Colony')
('17', 'RPF Training Centre')
('17', 'Upparguda X Road')
('17', 'ZTS Bus Stop')
('17', 'ZTC Bus Stop')
('17', 'APIIC Colony (ZTS)')
('17', 'HB Colony 1st Phase')
('17', 'NRM College Bus Stop')
('17', 'HB Colony')
('17', 'APHB Colony')
('17', 'Vasanth Vihar Colony')
('17', 'S.P. Nagar Bus Stop')
('17', 'Kushaiguda Depot')
('17', 'South Kamalanagar Bus Stop')
('17', 'ECIL')
('17', 'ECIL Cross Roads Bus Stop')
('17', 'Kushaiguda Bus Stop')
('300', 'Secunderabad/Chilkalguda Circle Bus Stop')
('300', 'Alugadda Baavi South Bus Stop')
('300', 'Mettuguda')
('300', 'NIN/Water Tank Bus Stop')
('300', 'Tarnaka Bus Stop')
('300', 'Tarnaka')
('300', 'Habsiguda Bus Stop')
('300', 'National Geophysical Research Institute (NGRI)')
('300', 'Junior College')
('300', 'Survey Of India Bus Stop')
('300', 'Uppal Circle Bus Stop')
('300', 'Uppal Circle Bus Stop')
('300', 'Uppal')
('300', 'Saraswathi Nagar')
('300', 'Mamatha Nagar Colony')
('300', 'Nagole Bus Stand')
('300', 'Snehapuri Colony')
('300', 'Alkapuri Bus Stop')
('300', 'Rajeev Gandhi Nagar')
('300', 'Mansoorabad Kamineni Hospital')
('300', 'Central Bank Colony')
('300', 'LB Nagar Ring Road Bus Stop')
('300', 'Sagar X Road Bus Stop')
('300', 'Gayatri Nagar X Road')
('300', 'Manda Mallamma Bus Stop')
('300', 'Owaisi Hospital')
('300', 'Pisalabanda')
('300', 'DRDL')
('300', 'Pgad / ASL')
('300', 'Hafiz Baba Nagar Bus Stop')
('300', 'Baba Nagar')
('300', 'DLRL')
('300', 'Junction Bus Stop')
('300', 'Keshavagiri')
('300', 'Laxmi Guda')
('300', 'Bandlaguda')
('300', 'Odamgudda')
('300', 'Mylardevpally Bus Stop')
('300', 'Durganagar')
('300', 'Shivam Pally')
('300', 'Babul Reddy Nagar')
('300', 'Aramghar')
('300', 'Aram Ghar -Mehidipatnam Bus Stop')
('300', 'Shivarampally X Road')
('300', 'Shivarampally Quarters')
('300', 'Dairy Farm Bus Stop')
('300', 'Happy Home Bus Stop')
('300', 'Upperpally X Road')
('300', 'Ring Road Bus Stop')
('300', 'Hyderguda')
('300', 'Tejaswi Nagar')
('300', 'Attapur')
('300', 'Ringroad')
('300', 'Jyothi Nagar')
('300', 'Maruthi Nagar')
('300', 'Lakshminagar Bus Stop')
('300', 'Retibowli Bus Stop')
('300', 'Mehdipatnam Bus Stop')
('113m', 'Mehdipatnam Bus Stop')
('113m', 'Sarojini Bus Stop')
('113m', 'NMDC Bus Stop')
('113m', 'Masab Tank')
('113m', 'Golconda Hotel')
('113m', 'Mahavir Bus Stop')
('113m', 'Masab Tank Bus Stop')
('113m', 'A.C. Guards')
('113m', 'Lakdikapul Bus Stop')
('113m', 'Lakdi Ka Pul')
('113m', 'Saifabad Bus Stop')
('113m', 'Telephone Bhavan Bus Stop')
('113m', 'Secretariat')
('113m', 'TSRTC Pushpak')
('113m', 'Liberty Bus Stop')
('113m', 'Liberty 1')
('113m', 'Himayath Nagar Bus Stop')
('113m', 'Narayanguda Bus Stop')
('113m', 'Chikkadpally')
('113m', 'Baghlingampally')
('113m', 'Barkatpura Bus Stop')
('113m', 'Fever Hospital Bus Stop')
('113m', 'Tilak Nagar Bus Stop')
('113m', '6 Number')
('113m', '6 Number')
('113m', 'Sree Ramana Bus Stop')
('113m', 'Gandhi Statue')
('113m', 'Irani Hotel Bus Stop')
('113m', 'TV Studio Ramanthapur Bus Stop')
('113m', 'Ramanthapur')
('113m', 'Ramanthapur Colony Bus Stop')
('113m', 'Ramanthapur Hyderabad Public School')
('113m', 'Ramanthapur Church')
('113m', 'Modern Foods')
('113m', 'Uppal X Roads')
('113m', 'Chilkanagar Bus Stop')
('113m', 'Uppal Gandhi Statue')
('113m', 'Uppal Bus Stop')
('113m', 'Uppal')
('279', 'Ibrahimpatnam Bus Depot')
('279', 'Ambedkar Statue')
('279', 'Sheriguda Bus Stop')
('279', 'Sri Indu College')
('279', 'Mangalpally X Roads Bus Stop')
('279', 'Koheda X Road')
('279', 'Bongulur X Roads Bus Stop')
('279', 'Manneguda')
('279', 'Ragannaguda')
('279', 'Brahmanapally')
('279', 'Turkayamjal Bus Stop')
('279', 'Injapur Cheruvu Katta')
('279', 'Injapur Bus Stop')
('279', 'Gurram Guda')
('279', 'Swami Narayana Colony')
('279', 'Sagar Complex Bus Stop')
('279', 'BN Reddy Nagar')
('279', 'BN Reddy Nagar')
('279', 'Teachers Colony 4th Phase')
('279', 'Hasthinapuram South')
('279', 'Hastinapuram Bus stop')
('279', 'Hastinapuram North Bus Stop')
('279', 'Omkar Nagar')
('279', 'Sagar X Road Bus Stop')
('279', 'L.B. Nagar Ring Road')
('279', 'LB Nagar Anutex / Uppal')
('279', 'Central Bank Colony')
('279', 'Kamineni Bus Stop')
('279', 'Rajeev Gandhi Nagar')
('279', 'Alkapuri Bus Stop')
('279', 'Snehapuri Uppal')
('279', 'Nagole Ring Road')
('279', 'Mamatha Nagar Colony')
('279', 'Saraswathi Nagar')
('279', 'Uppal Pushpak')
('279', 'Uppal X Road Bus Stop')
('279', 'Uppal Circle Bus Stop')
('279', 'Survey of India')
('279', 'National Geophysical Research Institute Bus Stop')
('279', 'Habsiguda Bus Stop')
('279', 'IICT')
('279', 'Tarnaka')
('279', 'Tarnaka X Road')
('279', 'Railway Degree College Bus Stop')
('279', 'Mettuguda')
('279', 'Alugadda Baavi South Bus Stop')
('279', 'Chilakalaguda')
('299h', 'Koti Womens College')
('299h', 'Chaderghat Bus Stop')
('299h', 'Nalgonda Cross Roads')
('299h', 'Malakpet')
('299h', 'Super Bazar Bus Stop')
('299h', 'Moosarambagh Bus Stop')
('299h', 'Dilsukhnagar')
('299h', 'Chaitanyapuri X Road')
('299h', 'Chaitanyapuri')
('299h', 'Kothapet')
('299h', 'Kothapet Bus Stop')
('299h', 'Asta Lakshmi Bus Stop')
('299h', 'Green Hills Colony')
('299h', 'Doctors Colony Bus Stop')
('299h', 'LB Nagar Bus Stop')
('299h', 'LB Nagar Ring Road Bus Stop')
('299h', 'L.B. Nagar Vijayalaxmi Theatre')
('299h', 'Check Post Bus Stop')
('299h', 'Chinthalkunta Bus Stop')
('299h', 'Vishnu Theatre')
('299h', 'Panama Godowns')
('299h', 'Sushma Theatre')
('299h', 'Autonagar')
('299h', 'High Court Colony Deer Park')
('299h', 'Bhagyalatha')
('299h', 'Lecturers Colony')
('299h', 'Lecturers Colony Bus Stop')
('104r', 'Koti Womens College')
('104r', 'Koti Bus Terminal')
('104r', 'Koti Bus Stop')
('104r', 'Koti')
('104r', 'Putlibowli Bus Stop')
('104r', 'Chaderghat')
('104r', 'Chaderghat Bus Stop')
('104r', 'Nalgonda Cross Roads')
('104r', 'Sohail Hotel Bus Stop')
('104r', 'Chanchalguda')
('104r', 'Chanchalguda Jail')
('104r', 'Saidabad')
('104r', 'Saidabad X Road')
('104r', 'Saidabad Bus Stop')
('104r', 'IS Sadan')
('104r', 'IS Sadan / Santosh Nagar')
('104r', 'Champapet (Brilliant GL School)')
('104r', 'RTC Colony (Champapet)')
('104r', 'Green Park Colony Bus Stop')
('104r', 'Karmanghat X Road')
('104r', 'Kranti Nagar')
('104r', 'Gayatri Nagar X Road')
('104r', 'Jillelguda')
('104r', 'Lalitha Nagar X Road')
('104r', 'Meerpet X Road')
('104r', 'TKR Bus Stop')
('5k', 'Secunderabad Bus Station 2')
('5k', 'Clock Tower')
('5k', 'Patny Center')
('5k', 'Bata')
('5k', 'Bible House')
('5k', 'Boats Club')
('5k', 'Boats Club (RP Road)')
('5k', 'Tank Bund')
('5k', 'DBR Mills')
('5k', 'LIC Zonal Office')
('5k', 'Accountant General (A & G) Office / Birla Mandir')
('5k', 'Lakdikapul Bus Stop')
('5k', 'AC Guards')
('5k', 'Masab Tank Puspak')
('5k', 'Mahavir Bus Stop')
('5k', 'Golconda Hotel')
('5k', 'Potti Sriramulu Nagar Bus Stop')
('5k', 'Masab Tank')
('5k', 'NMDC Bus Stop')
('5k', 'Sarojini Devi Eye Hospital')
('5k', 'Humayun Nagar Police Station Bus Stop')
('5k', 'Mehdipatnam Bus Stop')
('72v', 'NGOs Colony Bus Stop')
('72v', 'Vanasthalipuram')
('72v', 'Ganesh Temple')
('72v', 'Panama Godown')
('72v', 'Chintalakunta')
('72v', 'LB Nagar Bus Stop')
('72v', 'Ramakrishnapuram (Kothapet)')
('72v', 'Kothapet Bus Stop')
('72v', 'Chaitanyapuri')
('72v', 'Dilsukhnagar Bus station')
('72v', 'Mosarambagh')
('72v', 'Saleem Nagar')
('72v', 'Malakpet')
('72v', 'Nalgonda X Roads Bus Stop')
('72v', 'Chaderghat Bus Stop')
('72v', 'Osmanpura Colony')
('72v', 'Azampura')
('72v', 'Salar jung Museum (Darulshifa)')
('72v', 'Darulshifa')
('72v', 'Chatta Bazaar')
('72v', 'Pathar Gatti')
('72v', 'Char Kaman')
('72v', 'Charminar Bus Stop')
('72v', 'Khilwat')
('72v', 'Shah ali banda New Bus Stop')
('103', 'Koti Womens College')
('103', 'Koti Bus Terminal')
('103', 'Koti Bus Stop')
('103', 'Koti')
('103', 'Putlibowli Bus Stop')
('103', 'Chaderghat')
('103', 'Chaderghat Bus Stop')
('103', 'Nalgonda Cross Roads')
('103', 'Sohail Hotel Bus Stop')
('103', 'Chanchalguda')
('103', 'Chanchalguda Jail')
('103', 'Saidabad')
('103', 'Saidabad X Road')
('103', 'Saidabad Bus Stop')
('103', 'IS Sadan')
('103', 'IS Sadan / Santosh Nagar')
('103', 'Champapet (Brilliant GL School)')
('103', 'Champapet Gandhi Putla')
('103', 'Owaisi Hospital')
('103', 'Midani X Roads')
('103', 'DRDL')
('103', 'Hafiz Baba Nagar Bus Stop')
('103', 'Baba Nagar')
('103', 'Junction Bus Stop')
('103', 'Keshavagiri')
('103', 'Chandrayan Gutta Police Station Bus Stop')
('103', 'Chandrayanagutta')
('103', 'Abbas Stadium Barkas')
('103', 'Barkas')
('103', 'Peli Darga')
('103', 'Yerrakunta X Road')
('103', 'Sadath Nagar')
('103', 'Shaheen Nagar / Osmania Hotel')
('103', 'Quba Colony')
('103', 'Quba Colony')
('103', 'Jalapalli')
('103', 'Pahadi Sharif')
('229', 'Secunderabad Bus Station 2')
('229', 'Clock Tower')
('229', 'Patny Center')
('229', 'Manju Theater')
('229', 'Swapnalok Complex')
('229', 'Paradise')
('229', 'Paradise Bus Stop')
('229', 'Airport Backside')
('229', 'TadBund Bus Stop')
('229', 'Ashish Gardens Bus Stop')
('229', 'Chinna Thokata')
('229', 'New Bowenpally Bus Stop')
('229', 'Priyadarshini Hotel Bus Stop')
('229', 'MMR Garden Bus Stop')
('229', 'Military Dairy Farm')
('229', 'Suchitra Circle')
('229', 'Jeedimetla Village Bus Stop')
('229', 'Santa Sriram Estate')
('229', 'NCL Balaji Hospital')
('229', 'Ganga Enclave')
('229', 'NCL')
('229', 'Cine Planet Kompally')
('229', 'Kompally')
('229', 'Kompaly Bus Stand')
('229', 'Dollapally X Road / Kompally Chorwsta')
('229', 'Bank Bus Stop')
('229', 'Vaishnavi Constructions Bus Stop')
('229', 'Kompally Bridge')
('229', 'Farm Area Bus Stop')
('229', 'Devaraya')
('229', 'Gpochampalli Bus Stop')
('229', 'Gundla Pochampally')
('229', 'Prestige')
('229', 'Kandlakoya Bus Stop')
('229', 'CMR College of Engineering and Technology')
('229', 'Medchal Gubba')
('229', 'Medchal Chekpost')
('229', 'Medchal Bus Stop')
('229', 'Medchal Bus Terminal')
('6s', 'Secunderabad Railway Station Bus Stop')
('6s', 'Rathi File Secunderabad')
('6s', 'Chilkalguda Cross Roads Bus Stop')
('6s', 'Chilkalguda South Bus Stop')
('6s', 'Sitafalmandi MMTS Bus Stop')
('6s', 'Myala Guda East Bus Stop')
('6s', 'Namalgundu')
('6s', 'Sredevi Nursing Home East Bus Stop')
('6s', 'Warasiguda Bus Stop')
('6s', 'Arts College Bus Stop')
('6s', 'Jamia Osmania Bus Stop')
('6s', 'Adikmet')
('6s', 'Vidhyanagar Bus Stop')
('6s', 'Shankar Mutt')
('6s', 'Nallakunta Bus Stop')
('6s', 'Fever Hospital Bus Stop')
('6s', 'Barkatpura')
('6s', 'Baghlingampally')
('6s', 'Chikkadpally')
('6s', 'Narayanaguda Bus Stop')
('6s', 'Himayat Nagar')
('6s', 'Liberty')
('6s', 'Liberty Bus Stop')
('6s', 'Telephone Bhavan')
('6s', 'Mahavir Bus Stop')
('6s', 'Golconda Hotel')
('6s', 'Potti Sriramulu Nagar Bus Stop')
('6s', 'NMDC Bus Stop')
('6s', 'Sarojini Devi Eye Hospital')
('6s', 'Humayun Nagar Police Station Bus Stop')
('6s', 'Mehdipatnam')
('6s', 'Rethi Bowli')
('6s', 'Nanal Nagar Bus Stop')
('6s', 'Salarjung Colony')
('6s', 'Flour Mill')
('6s', 'Langer Houz')
('505', 'Shankarpally')
('505', 'Shankarpally X Road')
('505', 'Bhulkapur')
('505', 'Mokhila')
('505', 'Poddutur')
('505', 'I.B.S.')
('505', 'Donthanpally X Road')
('505', 'Kollur X Road')
('505', 'Janawada X Road')
('505', 'Miyakhan Gadda')
('505', 'Lakeview Colony')
('505', 'Khanapur X Roads')
('505', 'Kokapet Sez Cross Road')
('505', 'CBIT Hostel')
('505', 'CBIT')
('505', 'MGIT')
('505', 'Ocean Park')
('505', 'Gandi Pet X Road')
('505', 'Magadha Village')
('505', 'Grape Garden')
('505', 'Kokapet X Road')
('505', 'Manchrevula X Road (Narsingi)')
('505', 'Narsingi')
('505', 'Hanuman Temple')
('505', 'Taramathi Baradari')
('505', 'Ibrahim Bagh')
('505', 'Ramdev Guda')
('505', 'Tippu Khan Bridge')
('505', 'Bapu Ghat')
('505', 'Langer Houz')
('505', 'Flour Mill')
('505', 'Flour Mill')
('505', 'Salarjung Colony')
('505', 'Nala Nagar')
('505', 'Rethibowli Bus Stop')
('505', 'Rethi Bowli')
('505', 'Mehdipatnam Bus Station')
('505', 'Mehdipatnam Bus Station')